##### Required ######
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
#####################

##### Color Scheme #####
[[plugins]]
repo = 'altercation/vim-colors-solarized'
########################

##### Unite #####
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]]
repo = 'basyura/unite-rails'
#################

##### Auto Complete #####
[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
#########################

##### Language #####
[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'


[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'cespare/vim-toml'
####################

##### Status Line #####
[[plugins]]
repo = 'itchyny/lightline.vim'
#######################

##### Syntax Check #####
[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'jceb/vim-hier'
# [[plugins]]
# repo = 'KazuakiM/vim-qfsigns'

# [[plugins]]
# repo = 'KazuakiM/vim-qfstatusline'

########################
