##### denite.nvim #####
[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
nnoremap <silent> <Leader>o :<C-u>Denite file_rec<CR>
nnoremap <silent> <Leader>m :<C-u>Denite file_mru<CR>
nnoremap <silent> <Leader>y :<C-u>Denite neoyank<CR>
nnoremap <silent> <Leader>l :<C-u>Denite line<CR>
nnoremap <silent> <Leader>g :<C-u>Denite grep<CR>
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_event = 'BufRead'
#######################

##### Go #####
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
##############

##### Ruby #####
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'
################

##### JavaScript #####
######################

##### Json #####
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
################

##### Toml #####
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
################

##### Haml #####
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'
################
