### dein ###
[[plugins]]
repo = 'Shougo/dein.vim'

### Color Scheme ###
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  syntax enable
  set background=dark
  let g:solarized_termtrans=1
  let g:solarized_termcolors=256
  au AutoCmd VimEnter * nested colorscheme solarized
'''

### Unite ###
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
  au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
  nnoremap <silent> <buffer> <Space>f :<C-u>Unite file<CR>
  nnoremap <silent> <buffer> <Space>h :<C-u>Unite history/yank<CR>
  nnoremap <silent> <buffer> <Space>m :<C-u>Unite file_mru<CR>
'''

### Unite Source ###
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

### Auto Complete ###
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add ='''
  let g:deoplete#enable_at_startup = 1
'''

### for Ruby ###
[[plugins]]
repo = 'basyura/unite-rails'
